[project]
name = "medsearch"
version = "0.1.0"
description = "main source folder"
authors = [
    {name = "cubahiro",email = "cubahiro@proton.me"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ruff (>=0.16.0,<0.17.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "mypy (>=2.3.0,<3.0.0)",
    "elasticsearch (>=8.17.0,<9.0.0)",
    "fastapi[standard] (>=0.141.1,<0.142.0)",
    "pandas (>=3.0.5,<4.0.0)",
    "rich (>=15.0.0,<16.0.0)",
    "download (>=0.3.5,<0.4.0)",
    "pymupdf (>=1.28.0,<2.0.0)",
    "pydantic (>=2.13.4,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel (>=7.3.0,<8.0.0)"
]
